#ifndef GUARD_JOHTOMAPSEC_H
#define GUARD_JOHTOMAPSEC_H

#define MAPSEC_NEW_BARK_TOWN				0x00
#define MAPSEC_CHERRYGROVE_CITY				0x01
#define MAPSEC_VIOLET_CITY					0x02
#define MAPSEC_AZALEA_TOWN					0x03
#define MAPSEC_CIANWOOD_CITY				0x04
#define MAPSEC_GOLDENROD_CITY				0x05
#define MAPSEC_OLIVINE_CITY					0x06
#define MAPSEC_ECRUTEAK_CITY				0x07
#define MAPSEC_MAHOGANY_TOWN				0x08
#define MAPSEC_LAKE_OF_RAGE					0x09
#define MAPSEC_BLACKTHORN_CITY				0x0A
#define MAPSEC_MT_SILVER					0x0B
#define MAPSEC_PALLET_TOWN_GS               0x0C
#define MAPSEC_VIRIDIAN_CITY_GS             0x0D
#define MAPSEC_PEWTER_CITY_GS               0x0E
#define MAPSEC_CERULEAN_CITY_GS             0x0F
#define MAPSEC_LAVENDER_TOWN_GS             0x10
#define MAPSEC_VERMILION_CITY_GS            0x11
#define MAPSEC_CELADON_CITY_GS              0x12
#define MAPSEC_FUCHSIA_CITY_GS              0x13
#define MAPSEC_CINNABAR_ISLAND_GS           0x14
#define MAPSEC_INDIGO_PLATEAU_GS            0x15
#define MAPSEC_SAFFRON_CITY_GS              0x16
#define MAPSEC_ROUTE_4_FLYDUP_GS            0x17
#define MAPSEC_ROUTE_10_FLYDUP_GS           0x18
#define MAPSEC_ROUTE_1_GS                   0x19
#define MAPSEC_ROUTE_2_GS                   0x1A
#define MAPSEC_ROUTE_3_GS                   0x1B
#define MAPSEC_ROUTE_4_GS                   0x1C
#define MAPSEC_ROUTE_5_GS                   0x1D
#define MAPSEC_ROUTE_6_GS                   0x1E
#define MAPSEC_ROUTE_7_GS                   0x1F
#define MAPSEC_ROUTE_8_GS                   0x20
#define MAPSEC_ROUTE_9_GS                   0x21
#define MAPSEC_ROUTE_10_GS                  0x22
#define MAPSEC_ROUTE_11_GS                  0x23
#define MAPSEC_ROUTE_12_GS                  0x24
#define MAPSEC_ROUTE_13_GS                  0x25
#define MAPSEC_ROUTE_14_GS                  0x26
#define MAPSEC_ROUTE_15_GS                  0x27
#define MAPSEC_ROUTE_16_GS                  0x28
#define MAPSEC_ROUTE_17_GS                  0x29
#define MAPSEC_ROUTE_18_GS                  0x2A
#define MAPSEC_ROUTE_19_GS                  0x2B
#define MAPSEC_ROUTE_20_GS                  0x2C
#define MAPSEC_ROUTE_21_GS                  0x2D
#define MAPSEC_ROUTE_22_GS                  0x2E
#define MAPSEC_ROUTE_23_GS                  0x2F
#define MAPSEC_ROUTE_24_GS                  0x30
#define MAPSEC_ROUTE_25_GS                  0x31
#define MAPSEC_ROUTE_26						0x32
#define MAPSEC_ROUTE_27						0x33
#define MAPSEC_ROUTE_28						0x34
#define MAPSEC_ROUTE_29						0x35
#define MAPSEC_ROUTE_30						0x36
#define MAPSEC_ROUTE_31						0x37
#define MAPSEC_ROUTE_32						0x38
#define MAPSEC_ROUTE_33						0x39
#define MAPSEC_ROUTE_34						0x3A
#define MAPSEC_ROUTE_35						0x3B
#define MAPSEC_ROUTE_36						0x3C
#define MAPSEC_ROUTE_37						0x3D
#define MAPSEC_ROUTE_38						0x3E
#define MAPSEC_ROUTE_39						0x3F
#define MAPSEC_ROUTE_40						0x40
#define MAPSEC_ROUTE_41						0x41
#define MAPSEC_ROUTE_42						0x42
#define MAPSEC_ROUTE_43						0x43
#define MAPSEC_ROUTE_44						0x44
#define MAPSEC_ROUTE_45						0x45
#define MAPSEC_ROUTE_46						0x46
#define MAPSEC_ROUTE_47						0x47
#define MAPSEC_ROUTE_48						0x48
#define MAPSEC_DIGLETTS_CAVE_GS             0x49
#define MAPSEC_MT_MOON_GS                   0x4A
#define MAPSEC_ANCIENT_TOMB_GS              0x4B
#define MAPSEC_CERULEAN_CAVE_GS             0x4C
#define MAPSEC_ROCK_TUNNEL_GS               0x4D
#define MAPSEC_POWER_PLANT_GS               0x4E
#define MAPSEC_KANTO_SAFARI_ZONE_GS         0x4F
#define MAPSEC_POKEMON_LEAGUE_GS            0x50
#define MAPSEC_SEAFOAM_ISLANDS_GS           0x51
#define MAPSEC_ISLAND_CAVE_GS               0x52
#define MAPSEC_SPROUT_TOWER					0x53
#define MAPSEC_TIN_TOWER					0x54
#define MAPSEC_BURNED_TOWER					0x55
#define MAPSEC_NATIONAL_PARK				0x56
#define MAPSEC_RADIO_TOWER	                0x57
#define MAPSEC_RUINS_OF_ALPH                0x58
#define MAPSEC_UNION_CAVE                   0x59
#define MAPSEC_SLOWPOKE_WELL                0x5A
#define MAPSEC_LIGHTHOUSE                   0x5B
#define MAPSEC_ROCKET_HQ                    0x5C
#define MAPSEC_ILEX_FOREST                  0x5D
#define MAPSEC_GOLDENROD_TUNNEL             0x5E
#define MAPSEC_MT_MORTAR                    0x5F
#define MAPSEC_ICE_PATH                     0x60
#define MAPSEC_WHIRL_ISLANDS                0x61
#define MAPSEC_MT_SILVER_CAVE               0x62
#define MAPSEC_SILVER_RUINS					0x63
#define MAPSEC_DARK_CAVE                    0x64
#define MAPSEC_KANTO_VICTORY_ROAD_GS        0x65
#define MAPSEC_DRAGONS_DEN                  0x66
#define MAPSEC_TOHJO_FALLS                  0x67
#define MAPSEC_VIRIDIAN_FOREST_GS           0x68
#define MAPSEC_CONTEST_HALL			        0x69
#define MAPSEC_S_S_AQUA                     0x6A
#define MAPSEC_TRAINER_HILL_GS              0x6B
#define MAPSEC_CLIFF_CAVE				    0x6C
#define MAPSEC_FRONTIER_ACCESS				0X6D
#define MAPSEC_BATTLE_FRONTIER_GS           0x6E
#define MAPSEC_BELLCHIME_TRAIL		        0x6F
#define MAPSEC_SEALED_CHAMBER_GS            0x70
#define MAPSEC_EMBEDDED_TOWER		        0x71
#define MAPSEC_CLIFF_EDGE_GATE              0x72
#define MAPSEC_BIRTH_ISLAND_GS              0x73
#define MAPSEC_FARAWAY_ISLAND_GS            0x74
#define MAPSEC_ARTISAN_CAVE_GS              0x75
#define MAPSEC_ALTERING_CAVE_GS             0x76
#define MAPSEC_RADIO_TOWER_KANTO            0x77
#define MAPSEC_UNDERGROUND_PATH_GS          0x78
#define MAPSEC_SILPH_CO_GS                  0x79
#define MAPSEC_SPECIAL_AREA_GS              0x7A
#define MAPSEC_NONE_GS						0x7B

#endif //GUARD_JOHTOMAPSEC_H
