#ifndef GUARD_ORREMAPSEC_H
#define GUARD_ORREMAPSEC_H

#define MAPSEC_DISTANT_LAND                 0x00
#define MAPSEC_OUTSKIRT_STAND_1             0x01
#define MAPSEC_OUTSKIRT_STAND_2             0x02
#define MAPSEC_PHENAC_CITY_1                0x03
#define MAPSEC_PHENAC_CITY_2                0x04
#define MAPSEC_MAYORS_HOUSE_1	            0x05
#define MAPSEC_MAYORS_HOUSE_2               0x06
#define MAPSEC_ORRE_07                      0x07
#define MAPSEC_CIPHER_LAB_1                 0x08
#define MAPSEC_CIPHER_LAB_2                 0x09
#define MAPSEC_CIPHER_LAB_3                 0x0A
#define MAPSEC_CIPHER_LAB_4                 0x0B
#define MAPSEC_ORRE_0C                      0x0C
#define MAPSEC_ORRE_0D                      0x0D
#define MAPSEC_ORRE_0E                      0x0E
#define MAPSEC_PYRITE_TOWN_1                0x0F
#define MAPSEC_ORRE_10                      0x10
#define MAPSEC_ORRE_11                      0x11
#define MAPSEC_ORRE_12                      0x12
#define MAPSEC_ORRE_13                      0x13
#define MAPSEC_ORRE_14                      0x14
#define MAPSEC_ORRE_15                      0x15
#define MAPSEC_ORRE_16                      0x16
#define MAPSEC_ORRE_17                      0x17
#define MAPSEC_ORRE_18                      0x18
#define MAPSEC_PYRITE_BLDG_1                0x19
#define MAPSEC_ORRE_1A                      0x1A
#define MAPSEC_ORRE_1B                      0x1B
#define MAPSEC_PYRITE_BLDG_2                0x1C
#define MAPSEC_PYRITE_CAVE_1                0x1D
#define MAPSEC_MIRORS_HIDEOUT               0x1E
#define MAPSEC_PYRITE_CAVE_2                0x1F
#define MAPSEC_PYRITE_CAVE_3                0x20
#define MAPSEC_ORRE_21                      0x21
#define MAPSEC_ORRE_22                      0x22
#define MAPSEC_ORRE_23                      0x23
#define MAPSEC_ORRE_24                      0x24
#define MAPSEC_ORRE_25                      0x25
#define MAPSEC_ORRE_26                      0x26
#define MAPSEC_AGATE_VILLAGE                0x27
#define MAPSEC_ORRE_28                      0x28
#define MAPSEC_ORRE_29                      0x29
#define MAPSEC_ORRE_2A                      0x2A
#define MAPSEC_ORRE_2B                      0x2B
#define MAPSEC_ORRE_2C                      0x2C
#define MAPSEC_TOWER_COLOSSEUM_1            0x2D
#define MAPSEC_ORRE_2E                      0x2E
#define MAPSEC_THE_UNDER_1                  0x2F
#define MAPSEC_ORRE_30                      0x30
#define MAPSEC_ORRE_31                      0x31
#define MAPSEC_ORRE_32                      0x32
#define MAPSEC_ORRE_33                      0x33
#define MAPSEC_ORRE_34                      0x34
#define MAPSEC_ORRE_35                      0x35
#define MAPSEC_ORRE_36   			        0x36
#define MAPSEC_THE_UNDER_2                  0x37
#define MAPSEC_ORRE_38                      0x38
#define MAPSEC_ORRE_39                      0x39
#define MAPSEC_THE_UNDER_SUBWAY             0x3A
#define MAPSEC_REALGAM_TOWER_1              0x3B
#define MAPSEC_ORRE_3C                      0x3C
#define MAPSEC_ORRE_3D                      0x3D
#define MAPSEC_ORRE_3E                      0x3E
#define MAPSEC_ORRE_3F                      0x3F
#define MAPSEC_CIPHER_KEY_LAIR_1  	        0x40
#define MAPSEC_CIPHER_KEY_LAIR_2            0x41
#define MAPSEC_CIPHER_KEY_LAIR_3            0x42
#define MAPSEC_ORRE_MULTI_USE_43            0x43
#define MAPSEC_LABORATORY_1                 0x44
#define MAPSEC_LABORATORY_2	                0x45
#define MAPSEC_CIPHER_KEY_LAIR_4            0x46
#define MAPSEC_CIPHER_KEY_LAIR_5            0x47
#define MAPSEC_ORRE_48                      0x48
#define MAPSEC_CITADARK_ISLE_1              0x49
#define MAPSEC_CITADARK_ISLE_2              0x4A
#define MAPSEC_CITADARK_ISLE_3              0x4B
#define MAPSEC_ORRE_MULTI_USE_4C            0x4C
#define MAPSEC_CITADARK_ISLE_4              0x4D
#define MAPSEC_ORRE_4E                      0x4E
#define MAPSEC_ORRE_4F   				    0x4F
#define MAPSEC_CITADARK_ISLE_5              0x50
#define MAPSEC_CITADARK_ISLE_6              0x51
#define MAPSEC_ORRE_52                      0x52
#define MAPSEC_ORRE_53                      0x53
#define MAPSEC_CITADARK_ISLE_7              0x54
#define MAPSEC_CITADARK_ISLE_8              0x55
#define MAPSEC_ORRE_56                      0x56
#define MAPSEC_CITADARK_ISLE_9              0x57
#define MAPSEC_CITADARK_ISLE_10             0x58
#define MAPSEC_ORRE_59                      0x59
#define MAPSEC_ROCK                         0x5A
#define MAPSEC_OASIS                        0x5B
#define MAPSEC_CAVE                         0x5C
#define MAPSEC_ORRE_5D                      0x5D
#define MAPSEC_PHENAC_CITY_3                0x5E
#define MAPSEC_ORRE_5F	                    0x5F
#define MAPSEC_PHENAC_CITY_4                0x60
#define MAPSEC_PHENAC_CITY_5                0x61
#define MAPSEC_ORRE_62                      0x62
#define MAPSEC_ORRE_63                      0x63
#define MAPSEC_PHENAC_CITY_6                0x64
#define MAPSEC_ORRE_65                      0x65
#define MAPSEC_ORRE_66                      0x66
#define MAPSEC_ORRE_67                      0x67
#define MAPSEC_REALGAM_TOWER_2              0x68
#define MAPSEC_ORRE_69                      0x69
#define MAPSEC_REALGAM_TOWER_3              0x6A
#define MAPSEC_PHENAC_CITY_7                0x6B
#define MAPSEC_ORRE_6C                      0x6C
#define MAPSEC_ORRE_MULTI_USE_6D            0x6D
#define MAPSEC_ORRE_MULTI_USE_6E            0x6E
#define MAPSEC_ORRE_MULTI_USE_6F            0x6F
#define MAPSEC_PYRITE_COLOSSEUM             0x70
#define MAPSEC_ORRE_71                      0x71
#define MAPSEC_ORRE_72                      0x72
#define MAPSEC_REALGAM_TOWER_4              0x73
#define MAPSEC_ORRE_74                      0x74
#define MAPSEC_REALGAM_TOWER_5              0x75
#define MAPSEC_TOWER_COLOSSEUM_2            0x76
#define MAPSEC_PYRITE_TOWN_2                0x77
#define MAPSEC_ORRE_78                      0x78
#define MAPSEC_ORRE_79                      0x79
#define MAPSEC_ORRE_7A                      0x7A
#define MAPSEC_ORRE_7B                      0x7B
#define MAPSEC_ORRE_7C                      0x7C
#define MAPSEC_DEEP_COLOSSEUM               0x7D
#define MAPSEC_ORRE_7E                      0x7E
#define MAPSEC_ORRE_7F                      0x7F
#define MAPSEC_PHENAC_CITY_8                0x80
#define MAPSEC_ORRE_81		                0x81
#define MAPSEC_ORRE_82                      0x82
#define MAPSEC_ORRE_83                      0x83
#define MAPSEC_SNAGEM_HIDEOUT_1             0x84
#define MAPSEC_ORRE_85		                0x85
#define MAPSEC_SNAGEM_HIDEOUT_2             0x86
#define MAPSEC_ORRE_87                      0x87
#define MAPSEC_ORRE_88                      0x88
#define MAPSEC_ORRE_89                      0x89
#define MAPSEC_ORRE_8A                      0x8A
#define MAPSEC_ORRE_8B                      0x8B
#define MAPSEC_ORRE_8C                      0x8C
#define MAPSEC_ORRE_8D                      0x8D
#define MAPSEC_ORRE_8E                      0x8E
#define MAPSEC_POKEMON_HQ_LAB               0x8F
#define MAPSEC_ORRE_90                      0x90
#define MAPSEC_ORRE_91                      0x91
#define MAPSEC_ORRE_92                      0x92
#define MAPSEC_ORRE_93                      0x93
#define MAPSEC_ORRE_94                      0x94
#define MAPSEC_ORRE_95                      0x95
#define MAPSEC_ORRE_96                      0x96
#define MAPSEC_ORRE_97                      0x97
#define MAPSEC_ORRE_98                      0x98
#define MAPSEC_GATEON_PORT_1                0x99
#define MAPSEC_ORRE_9A                      0x9A
#define MAPSEC_ORRE_9B                      0x9B
#define MAPSEC_ORRE_9C                      0x9C
#define MAPSEC_ORRE_9D                      0x9D
#define MAPSEC_ORRE_9E                      0x9E
#define MAPSEC_ORRE_9F                      0x9F
#define MAPSEC_ORRE_A0                      0xA0
#define MAPSEC_ORRE_A1                      0xA1
#define MAPSEC_GATEON_PORT_2                0xA2
#define MAPSEC_ORRE_A3                      0xA3
#define MAPSEC_OUTSKIRT_STAND_3             0xA4
#define MAPSEC_ORRE_A5		                0xA5
#define MAPSEC_ORRE_A6		                0xA6
#define MAPSEC_ORRE_A7		                0xA7
#define MAPSEC_ORRE_A8		                0xA8
#define MAPSEC_ORRE_A9		                0xA9
#define MAPSEC_ORRE_AA		                0xAA
#define MAPSEC_ORRE_AB		                0xAB
#define MAPSEC_ORRE_AC		                0xAC
#define MAPSEC_ORRE_AD		                0xAD
#define MAPSEC_ORRE_AE		                0xAE
#define MAPSEC_ORRE_AF		                0xAF
#define MAPSEC_ORRE_B0		                0xB0
#define MAPSEC_ORRE_B1		                0xB1
#define MAPSEC_ORRE_B2		                0xB2
#define MAPSEC_ORRE_B3		                0xB3
#define MAPSEC_ORRE_B4		                0xB4
#define MAPSEC_ORRE_B5		                0xB5
#define MAPSEC_ORRE_B6		                0xB6
#define MAPSEC_ORRE_B7		                0xB7
#define MAPSEC_ORRE_B8		                0xB8
#define MAPSEC_ORRE_B9		                0xB9
#define MAPSEC_ORRE_BA		                0xBA
#define MAPSEC_ORRE_BB		                0xBB
#define MAPSEC_ORRE_BC		                0xBC
#define MAPSEC_ORRE_BD		                0xBD
#define MAPSEC_ORRE_BE		                0xBE
#define MAPSEC_ORRE_BF		                0xBF
#define MAPSEC_ORRE_C0		                0xC0
#define MAPSEC_ORRE_C1		                0xC1
#define MAPSEC_ORRE_C2		                0xC2
#define MAPSEC_ORRE_C3		                0xC3
#define MAPSEC_ORRE_C4		                0xC4
#define MAPSEC_ORRE_C5		                0xC5
#define MAPSEC_ORRE_C6		                0xC6
#define MAPSEC_ORRE_C7		                0xC7
#define MAPSEC_ORRE_C8		                0xC8
#define MAPSEC_ORRE_C9		                0xC9
#define MAPSEC_ORRE_CA		                0xCA
#define MAPSEC_ORRE_CB		                0xCB
#define MAPSEC_ORRE_CC		                0xCC
#define MAPSEC_ORRE_CD		                0xCD
#define MAPSEC_ORRE_CE		                0xCE
#define MAPSEC_ORRE_CF		                0xCF
#define MAPSEC_ORRE_D0		                0xD0
#define MAPSEC_ORRE_D1		                0xD1
#define MAPSEC_ORRE_D2		                0xD2
#define MAPSEC_ORRE_D3		                0xD3
#define MAPSEC_ORRE_D4		                0xD4
#define MAPSEC_ORRE_D5		                0xD5
#define MAPSEC_ORRE_D6		                0xD6
#define MAPSEC_ORRE_D7		                0xD7
#define MAPSEC_ORRE_D8		                0xD8
#define MAPSEC_ORRE_D9		                0xD9
#define MAPSEC_ORRE_DA		                0xDA
#define MAPSEC_ORRE_DB		                0xDB
#define MAPSEC_ORRE_DC		                0xDC
#define MAPSEC_ORRE_DD		                0xDD
#define MAPSEC_ORRE_DE		                0xDE
#define MAPSEC_ORRE_DF		                0xDF
#define MAPSEC_ORRE_E0		                0xE0
#define MAPSEC_ORRE_E1		                0xE1
#define MAPSEC_ORRE_E2		                0xE2
#define MAPSEC_ORRE_E3		                0xE3
#define MAPSEC_ORRE_E4		                0xE4

#define MAPSEC_ORRE_SPECIAL					0xFE

#endif //GUARD_ORREMAPSEC_H
