#ifndef GUARD_CONSTANTS_SONGS_H
#define GUARD_CONSTANTS_SONGS_H

#define MUS_DUMMY                 0   // MUS_DUMMY
#define SE_USE_ITEM               1   // SE_KAIFUKU
#define SE_PC_LOGIN               2   // SE_PC_LOGIN
#define SE_PC_OFF                 3   // SE_PC_OFF
#define SE_PC_ON                  4   // SE_PC_ON
#define SE_SELECT                 5   // SE_SELECT
#define SE_WIN_OPEN               6   // SE_WIN_OPEN
#define SE_WALL_HIT               7   // SE_WALL_HIT
#define SE_RS_DOOR                8   // SE_DOOR
#define SE_EXIT                   9   // SE_KAIDAN
#define SE_LEDGE                  10  // SE_DANSA
#define SE_BIKE_BELL              11  // SE_JITENSYA
#define SE_NOT_EFFECTIVE          12  // SE_KOUKA_L
#define SE_EFFECTIVE              13  // SE_KOUKA_M
#define SE_SUPER_EFFECTIVE        14  // SE_KOUKA_H
#define SE_BALL_OPEN              15  // SE_BOWA2
#define SE_FAINT                  16  // SE_POKE_DEAD
#define SE_FLEE                   17  // SE_NIGERU
#define SE_SLIDING_DOOR           18  // SE_JIDO_DOA
#define SE_SHIP                   19  // SE_NAMINORI
#define SE_BANG                   20  // SE_BAN
#define SE_PIN                    21  // SE_PIN
#define SE_BOO                    22  // SE_BOO
#define SE_BALL                   23  // SE_BOWA
#define SE_CONTEST_PLACE          24  // SE_JYUNI
#define SE_SUCCESS                25  // SE_SEIKAI
#define SE_FAILURE                26  // SE_HAZURE
#define SE_EXP                    27  // SE_EXP
#define SE_BIKE_HOP               28  // SE_JITE_PYOKO
#define SE_SWITCH                 29  // SE_MU_PACHI
#define SE_CLICK                  30  // SE_TK_KASYA
#define SE_CONTEST_CONDITION_LOSE 31  // SE_FU_ZAKU2
#define SE_LAVARIDGE_FALL_WARP    32  // SE_FU_ZUZUZU
#define SE_ICE_STAIRS             33  // SE_RU_GASHIN
#define SE_ICE_BREAK              34  // SE_RU_GASYAN
#define SE_ICE_CRACK              35  // SE_RU_BARI
#define SE_FALL                   36  // SE_RU_HYUU
#define SE_UNLOCK                 37  // SE_KI_GASYAN
#define SE_WARP_IN                38  // SE_TK_WARPIN
#define SE_WARP_OUT               39  // SE_TK_WARPOUT
#define SE_REPEL                  40  // SE_TU_SAA
#define SE_ROTATING_GATE          41  // SE_HI_TURUN
#define SE_TRUCK_MOVE             42 // SE_TRACK_MOVE
#define SE_BERRY_BLENDER          43  // SE_MOTER
#define SE_SAVE                   44  // SE_SAVE
#define SE_BALL_BOUNCE_1          45  // SE_KON
#define SE_BALL_BOUNCE_2          46  // SE_KON2
#define SE_BALL_BOUNCE_3          47  // SE_KON3
#define SE_BALL_BOUNCE_4          48  // SE_KON4
#define SE_BALL_TRADE             49  // SE_SUIKOMU
#define SE_BALL_THROW             50  // SE_NAGERU
#define SE_NOTE_C                 51  // SE_TOY_C
#define SE_NOTE_D                 52  // SE_TOY_D
#define SE_NOTE_E                 53  // SE_TOY_E
#define SE_NOTE_F                 54  // SE_TOY_F
#define SE_NOTE_G                 55  // SE_TOY_G
#define SE_NOTE_A                 56  // SE_TOY_A
#define SE_NOTE_B                 57  // SE_TOY_B
#define SE_NOTE_C_HIGH            58  // SE_TOY_C1
#define SE_PUDDLE                 59  // SE_MIZU
#define SE_BRIDGE_WALK            60  // SE_HASHI
#define SE_ITEMFINDER             61  // SE_DAUGI
#define SE_DING_DONG              62  // SE_PINPON
#define SE_BALLOON_RED            63  // SE_FUUSEN1
#define SE_BALLOON_BLUE           64  // SE_FUUSEN2
#define SE_BALLOON_YELLOW         65  // SE_FUUSEN3
#define SE_BREAKABLE_DOOR         66  // SE_TOY_KABE
#define SE_MUD_BALL               67  // SE_TOY_DANGO
#define SE_FIELD_POISON           68  // SE_DOKU
#define SE_ESCALATOR              69  // SE_ESUKA
#define SE_THUNDERSTORM           70  // SE_T_AME
#define SE_THUNDERSTORM_STOP      71  // SE_T_AME_E
#define SE_DOWNPOUR               72  // SE_T_OOAME
#define SE_DOWNPOUR_STOP          73  // SE_T_OOAME_E
#define SE_RAIN                   74  // SE_T_KOAME
#define SE_RAIN_STOP              75  // SE_T_KOAME_E
#define SE_THUNDER                76  // SE_T_KAMI
#define SE_THUNDER2               77  // SE_T_KAMI2
#define SE_ELEVATOR               78  // SE_ELEBETA
#define SE_LOW_HEALTH             79  // SE_HINSI
#define SE_EXP_MAX                80  // SE_EXPMAX
#define SE_ROULETTE_BALL          81  // SE_TAMAKORO
#define SE_ROULETTE_BALL2         82  // SE_TAMAKORO_E
#define SE_TAILLOW_WING_FLAP      83  // SE_BASABASA
#define SE_RS_SHOP                84  // SE_REGI
#define SE_CONTEST_HEART          85  // SE_C_GAJI
#define SE_CONTEST_CURTAIN_RISE   86  // SE_C_MAKU_U
#define SE_CONTEST_CURTAIN_FALL   87  // SE_C_MAKU_D
#define SE_CONTEST_ICON_CHANGE    88  // SE_C_PASI
#define SE_CONTEST_ICON_CLEAR     89  // SE_C_SYU
#define SE_CONTEST_MONS_TURN      90  // SE_C_PIKON
#define SE_SHINY                  91  // SE_REAPOKE
#define SE_MUGSHOT                92  // SE_BT_START
#define SE_APPLAUSE               93  // SE_DENDOU
#define SE_VEND                   94  // SE_JIHANKI
#define SE_ORB                    95 // SE_TAMA
#define SE_DEX_SCROLL             96 // SE_Z_SCROLL
#define SE_DEX_PAGE               97 // SE_Z_PAGE
#define SE_POKENAV_ON             98 // SE_PN_ON
#define SE_EGG_HATCH              99 // SE_TAMAGO
#define SE_BALL_TRAY_ENTER        100 // SE_TB_START
#define SE_BALL_TRAY_BALL         101 // SE_TB_KON
#define SE_BALL_TRAY_EXIT         102 // SE_TB_KARA
#define SE_GLASS_FLUTE            103 // SE_BIDORO
// Move SFX
#define SE_M_THUNDERBOLT          104 // SE_W085
#define SE_M_THUNDERBOLT2         105 // SE_W085B
#define SE_M_HARDEN               106 // SE_W231
#define SE_M_NIGHTMARE            107 // SE_W171
#define SE_M_VITAL_THROW          108 // SE_W233
#define SE_M_VITAL_THROW2         109 // SE_W233B
#define SE_M_BUBBLE               110 // SE_W145
#define SE_M_BUBBLE2              111 // SE_W145B
#define SE_M_BUBBLE3              112 // SE_W145C
#define SE_M_RAIN_DANCE           113 // SE_W240
#define SE_M_CUT                  114 // SE_W015
#define SE_M_STRING_SHOT          115 // SE_W081
#define SE_M_STRING_SHOT2         116 // SE_W081B
#define SE_M_ROCK_THROW           117 // SE_W088
#define SE_M_GUST                 118 // SE_W016
#define SE_M_GUST2                119 // SE_W016B
#define SE_M_DOUBLE_SLAP          120 // SE_W003
#define SE_M_DOUBLE_TEAM          121 // SE_W104
#define SE_M_RAZOR_WIND           122 // SE_W013
#define SE_M_ICY_WIND             123 // SE_W196
#define SE_M_THUNDER_WAVE         124 // SE_W086
#define SE_M_COMET_PUNCH          125 // SE_W004
#define SE_M_MEGA_KICK            126 // SE_W025
#define SE_M_MEGA_KICK2           127 // SE_W025B
#define SE_M_CRABHAMMER           128 // SE_W152
#define SE_M_JUMP_KICK            129 // SE_W026
#define SE_M_FLAME_WHEEL          130 // SE_W172
#define SE_M_FLAME_WHEEL2         131 // SE_W172B
#define SE_M_FLAMETHROWER         132 // SE_W053
#define SE_M_FIRE_PUNCH           133 // SE_W007
#define SE_M_TOXIC                134 // SE_W092
#define SE_M_SACRED_FIRE          135 // SE_W221
#define SE_M_SACRED_FIRE2         136 // SE_W221B
#define SE_M_EMBER                137 // SE_W052
#define SE_M_TAKE_DOWN            138 // SE_W036
#define SE_M_BLIZZARD             139 // SE_W059
#define SE_M_BLIZZARD2            140 // SE_W059B
#define SE_M_SCRATCH              141 // SE_W010
#define SE_M_VICEGRIP             142 // SE_W011
#define SE_M_WING_ATTACK          143 // SE_W017
#define SE_M_FLY                  144 // SE_W019
#define SE_M_SAND_ATTACK          145 // SE_W028
#define SE_M_RAZOR_WIND2          146 // SE_W013B
#define SE_M_BITE                 147 // SE_W044
#define SE_M_HEADBUTT             148 // SE_W029
#define SE_M_SURF                 149 // SE_W057
#define SE_M_HYDRO_PUMP           150 // SE_W056
#define SE_M_WHIRLPOOL            151 // SE_W250
#define SE_M_HORN_ATTACK          152 // SE_W030
#define SE_M_TAIL_WHIP            153 // SE_W039
#define SE_M_MIST                 154 // SE_W054
#define SE_M_POISON_POWDER        155 // SE_W077
#define SE_M_BIND                 156 // SE_W020
#define SE_M_DRAGON_RAGE          157 // SE_W082
#define SE_M_SING                 158 // SE_W047
#define SE_M_PERISH_SONG          159 // SE_W195
#define SE_M_PAY_DAY              160 // SE_W006
#define SE_M_DIG                  161 // SE_W091
#define SE_M_DIZZY_PUNCH          162 // SE_W146
#define SE_M_SELF_DESTRUCT        163 // SE_W120
#define SE_M_EXPLOSION            164 // SE_W153
#define SE_M_ABSORB_2             165 // SE_W071B
#define SE_M_ABSORB               166 // SE_W071
#define SE_M_SCREECH              167 // SE_W103
#define SE_M_BUBBLE_BEAM          168 // SE_W062
#define SE_M_BUBBLE_BEAM2         169 // SE_W062B
#define SE_M_SUPERSONIC           170 // SE_W048
#define SE_M_BELLY_DRUM           171 // SE_W187
#define SE_M_METRONOME            172 // SE_W118
#define SE_M_BONEMERANG           173 // SE_W155
#define SE_M_LICK                 174 // SE_W122
#define SE_M_PSYBEAM              175 // SE_W060
#define SE_M_FAINT_ATTACK         176 // SE_W185
#define SE_M_SWORDS_DANCE         177 // SE_W014
#define SE_M_LEER                 178 // SE_W043
#define SE_M_SWAGGER              179 // SE_W207
#define SE_M_SWAGGER2             180 // SE_W207B
#define SE_M_HEAL_BELL            181 // SE_W215
#define SE_M_CONFUSE_RAY          182 // SE_W109
#define SE_M_SNORE                183 // SE_W173
#define SE_M_BRICK_BREAK          184 // SE_W280
#define SE_M_GIGA_DRAIN           185 // SE_W202
#define SE_M_PSYBEAM2             186 // SE_W060B
#define SE_M_SOLAR_BEAM           187 // SE_W076
#define SE_M_PETAL_DANCE          188 // SE_W080
#define SE_M_TELEPORT             189 // SE_W100
#define SE_M_MINIMIZE             190 // SE_W107
#define SE_M_SKETCH               191 // SE_W166
#define SE_M_SWIFT                192 // SE_W129
#define SE_M_REFLECT              193 // SE_W115
#define SE_M_BARRIER              194// SE_W112
#define SE_M_DETECT               195 // SE_W197
#define SE_M_LOCK_ON              196 // SE_W199
#define SE_M_MOONLIGHT            197 // SE_W236
#define SE_M_CHARM                198 // SE_W204
#define SE_M_CHARGE               199 // SE_W268
#define SE_M_STRENGTH             200 // SE_W070
#define SE_M_HYPER_BEAM           201 // SE_W063
#define SE_M_WATERFALL            202 // SE_W127
#define SE_M_REVERSAL             203 // SE_W179
#define SE_M_ACID_ARMOR           204 // SE_W151
#define SE_M_SANDSTORM            205 // SE_W201
#define SE_M_TRI_ATTACK           206 // SE_W161
#define SE_M_TRI_ATTACK2          207 // SE_W161B
#define SE_M_ENCORE               208 // SE_W227
#define SE_M_ENCORE2              209 // SE_W227B
#define SE_M_BATON_PASS           210 // SE_W226
#define SE_M_MILK_DRINK           211 // SE_W208
#define SE_M_ATTRACT              212 // SE_W213
#define SE_M_ATTRACT2             213 // SE_W213B
#define SE_M_MORNING_SUN          214 // SE_W234
#define SE_M_FLATTER              215 // SE_W260
#define SE_M_SAND_TOMB            216 // SE_W328
#define SE_M_GRASSWHISTLE         217 // SE_W320
#define SE_M_SPIT_UP              218 // SE_W255
#define SE_M_DIVE                 219 // SE_W291
#define SE_M_EARTHQUAKE           220 // SE_W089
#define SE_M_TWISTER              221 // SE_W239
#define SE_M_SWEET_SCENT          222 // SE_W230
#define SE_M_YAWN                 223 // SE_W281
#define SE_M_SKY_UPPERCUT         224 // SE_W327
#define SE_M_STAT_INCREASE        225 // SE_W287
#define SE_M_HEAT_WAVE            226 // SE_W257
#define SE_M_UPROAR               227 // SE_W253
#define SE_M_HAIL                 228 // SE_W258
#define SE_M_COSMIC_POWER         229 // SE_W322
#define SE_M_TEETER_DANCE         230 // SE_W298
#define SE_M_STAT_DECREASE        231 // SE_W287B
#define SE_M_HAZE                 232 // SE_W114
#define SE_M_HYPER_BEAM2          233 // SE_W063B
// New FRLG SFX
#define SE_DOOR                   234 // SE_RG_W_DOOR
#define SE_CARD_FLIP              235 // SE_RG_CARD1
#define SE_CARD_FLIPPING          236 // SE_RG_CARD2
#define SE_CARD_OPEN              237 // SE_RG_CARD3
#define SE_BAG_CURSOR             238 // SE_RG_BAG1
#define SE_BAG_POCKET             239 // SE_RG_BAG2
#define SE_BALL_CLICK             240 // SE_RG_GETTING
#define SE_SHOP                   241 // SE_RG_SHOP
#define SE_SS_ANNE_HORN           242 // SE_RG_KITEKI
#define SE_HELP_OPEN              243 // SE_RG_HELP_OP
#define SE_HELP_CLOSE             244 // SE_RG_HELP_CL
#define SE_HELP_ERROR             245 // SE_RG_HELP_NG
#define SE_DEOXYS_MOVE            246 // SE_RG_DEOMOV
#define SE_POKE_JUMP_SUCCESS      247 // SE_RG_EXCELLENT
#define SE_POKE_JUMP_FAILURE      248 // SE_RG_NAWAMISS
// New Emerald SFX
#define SE_POKENAV_CALL           249 // SE_TOREEYE
#define SE_POKENAV_HANG_UP        250 // SE_TOREOFF
#define SE_ARENA_TIMEUP1          251 // SE_HANTEI1
#define SE_ARENA_TIMEUP2          252 // SE_HANTEI2
#define SE_PIKE_CURTAIN_CLOSE     253 // SE_CURTAIN
#define SE_PIKE_CURTAIN_OPEN      254 // SE_CURTAIN1
#define SE_SUDOWOODO_SHAKE        255 // SE_USSOKI
// Music kept from RS
#define MUS_HEAL                  256 // MUS_ME_ASA
#define MUS_LEVEL_UP              257 // MUS_FANFA1
#define MUS_OBTAIN_ITEM           258 // MUS_FANFA4
#define MUS_EVOLVED               259 // MUS_FANFA5
#define MUS_OBTAIN_BADGE          260 // MUS_ME_BACHI
#define MUS_OBTAIN_TMHM           261 // MUS_ME_WAZA
#define MUS_OBTAIN_BERRY          262 // MUS_ME_KINOMI
#define MUS_EVOLUTION_INTRO       263 // MUS_ME_SHINKA
#define MUS_EVOLUTION             264 // MUS_SHINKA
#define MUS_RS_VS_GYM_LEADER      265 // MUS_BATTLE32
#define MUS_RS_VS_TRAINER         266 // MUS_BATTLE20
#define MUS_SCHOOL                267 // MUS_P_SCHOOL
#define MUS_SLOTS_JACKPOT         268 // MUS_ME_B_BIG
#define MUS_SLOTS_WIN             269 // MUS_ME_B_SMALL
#define MUS_MOVE_DELETED          270 // MUS_ME_WASURE
#define MUS_TOO_BAD               271 // MUS_ME_ZANNEN
// New FRLG Music
#define MUS_FOLLOW_ME             272 // MUS_RG_ANNAI
#define MUS_GAME_CORNER           273 // MUS_RG_SLOT
#define MUS_ROCKET_HIDEOUT        274 // MUS_RG_AJITO
#define MUS_GYM                   275 // MUS_RG_GYM
#define MUS_JIGGLYPUFF            276 // MUS_RG_PURIN
#define MUS_INTRO_FIGHT           277 // MUS_RG_DEMO
#define MUS_TITLE                 278 // MUS_RG_TITLE
#define MUS_CINNABAR              279 // MUS_RG_GUREN
#define MUS_LAVENDER              280 // MUS_RG_SHION
#define MUS_HEAL_UNUSED           281 // MUS_RG_KAIHUKU
#define MUS_CYCLING               282 // MUS_RG_CYCLING
#define MUS_ENCOUNTER_ROCKET      283 // MUS_RG_ROCKET
#define MUS_ENCOUNTER_GIRL        284 // MUS_RG_SHOUJO
#define MUS_ENCOUNTER_BOY         285 // MUS_RG_SHOUNEN
#define MUS_HALL_OF_FAME          286 // MUS_RG_DENDOU
#define MUS_VIRIDIAN_FOREST       287 // MUS_RG_T_MORI
#define MUS_MT_MOON               288 // MUS_RG_OTSUKIMI
#define MUS_POKE_MANSION          289 // MUS_RG_POKEYASHI
#define MUS_CREDITS               290 // MUS_RG_ENDING
#define MUS_ROUTE1                291 // MUS_RG_LOAD01
#define MUS_ROUTE24               292 // MUS_RG_OPENING
#define MUS_ROUTE3                293 // MUS_RG_LOAD02
#define MUS_ROUTE11               294 // MUS_RG_LOAD03
#define MUS_VICTORY_ROAD          295 // MUS_RG_CHAMP_R
#define MUS_VS_GYM_LEADER         296 // MUS_RG_VS_GYM
#define MUS_VS_TRAINER            297 // MUS_RG_VS_TORE
#define MUS_VS_WILD               298 // MUS_RG_VS_YASEI
#define MUS_VS_CHAMPION           299 // MUS_RG_VS_LAST
#define MUS_PALLET                300 // MUS_RG_MASARA
#define MUS_OAK_LAB               301 // MUS_RG_KENKYU
#define MUS_OAK                   302 // MUS_RG_OHKIDO
#define MUS_POKE_CENTER           303 // MUS_RG_POKECEN
#define MUS_SS_ANNE               304 // MUS_RG_SANTOAN
#define MUS_SURF                  305 // MUS_RG_NAMINORI
#define MUS_POKE_TOWER            306 // MUS_RG_P_TOWER
#define MUS_SILPH                 307 // MUS_RG_SHIRUHU
#define MUS_FUCHSIA               308 // MUS_RG_HANADA
#define MUS_CELADON               309 // MUS_RG_TAMAMUSI
#define MUS_VICTORY_TRAINER       310 // MUS_RG_WIN_TRE
#define MUS_VICTORY_WILD          311 // MUS_RG_WIN_YASEI
#define MUS_VICTORY_GYM_LEADER    312 // MUS_RG_WIN_GYM
#define MUS_VERMILLION            313 // MUS_RG_KUCHIBA
#define MUS_PEWTER                314 // MUS_RG_NIBI
#define MUS_ENCOUNTER_RIVAL       315 // MUS_RG_RIVAL1
#define MUS_RIVAL_EXIT            316 // MUS_RG_RIVAL2
#define MUS_DEX_RATING            317 // MUS_RG_FAN2
#define MUS_OBTAIN_KEY_ITEM       318 // MUS_RG_FAN5
#define MUS_CAUGHT_INTRO          319 // MUS_RG_FAN6
#define MUS_PHOTO                 320 // MUS_ME_RG_PHOTO
#define MUS_GAME_FREAK            321 // MUS_RG_TITLEROG
#define MUS_CAUGHT                322 // MUS_RG_GET_YASEI
#define MUS_NEW_GAME_INSTRUCT     323 // MUS_RG_SOUSA
#define MUS_NEW_GAME_INTRO        324 // MUS_RG_SEKAIKAN
#define MUS_NEW_GAME_EXIT         325 // MUS_RG_SEIBETU
#define MUS_POKE_JUMP             326 // MUS_RG_JUMP
#define MUS_UNION_ROOM            327 // MUS_RG_UNION
#define MUS_NET_CENTER            328 // MUS_RG_NETWORK
#define MUS_MYSTERY_GIFT          329 // MUS_RG_OKURIMONO
#define MUS_BERRY_PICK            330 // MUS_RG_KINOMIKUI
#define MUS_SEVII_CAVE            331 // MUS_RG_NANADUNGEON
#define MUS_TEACHY_TV_SHOW        332 // MUS_RG_OSHIE_TV
#define MUS_SEVII_ROUTE           333 // MUS_RG_NANASHIMA
#define MUS_SEVII_DUNGEON         334 // MUS_RG_NANAISEKI
#define MUS_SEVII_123             335 // MUS_RG_NANA123
#define MUS_SEVII_45              336 // MUS_RG_NANA45
#define MUS_SEVII_67              337 // MUS_RG_NANA67
#define MUS_POKE_FLUTE            338 // MUS_RG_POKEFUE
#define MUS_VS_DEOXYS             339 // MUS_RG_VS_DEO
#define MUS_VS_MEWTWO             340 // MUS_RG_VS_MYU2
#define MUS_VS_LEGEND             341 // MUS_RG_VS_DEN
#define MUS_ENCOUNTER_GYM_LEADER  342 // MUS_RG_EXEYE
#define MUS_ENCOUNTER_DEOXYS      343 // MUS_RG_DEOEYE
#define MUS_TRAINER_TOWER         344 // MUS_RG_T_TOWER
#define MUS_SLOW_PALLET           345 // MUS_RG_SLOWMASARA
#define MUS_TEACHY_TV_MENU        346 // MUS_RG_TVNOIZE
#define MUS_ABANDONED_SHIP        347 // MUS_DAN02
#define MUS_B_TOWER_RS            348 // MUS_B_TOWER
#define MUS_B_FRONTIER            349 // MUS_B_FRONTIER
#define MUS_B_ARENA               350 // MUS_B_ARENA
#define MUS_OBTAIN_B_POINTS       351 // MUS_ME_POINTGET
#define MUS_REGISTER_MATCH_CALL   352 // MUS_ME_TORE_EYE
#define MUS_B_PYRAMID             353 // MUS_PYRAMID
#define MUS_B_PYRAMID_TOP         354 // MUS_PYRAMID_TOP
#define MUS_B_PALACE              355 // MUS_B_PALACE
#define MUS_B_TOWER               356 // MUS_SATTOWER
#define MUS_OBTAIN_SYMBOL         357 // MUS_ME_SYMBOLGET
#define MUS_B_DOME                358 // MUS_B_DOME
#define MUS_B_PIKE                359 // MUS_B_TUBE
#define MUS_B_FACTORY             360 // MUS_B_FACTORY
#define MUS_VS_FRONTIER_BRAIN     361 // MUS_VS_FRONT
#define MUS_VS_MEW                362 // MUS_VS_MEW
#define MUS_B_DOME_LOBBY          363 // MUS_B_DOME1

#define MUS_NONE                    0xFFFF

#endif  // GUARD_CONSTANTS_SONGS_H
